apiVersion: v1
kind: Service

metadata:
  name: woosso-service

spec:
  type: NodePort
  selector:
    app: woosso-backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000