spring:
  application:
    name: woosso


  datasource:
    url: jdbc:mysql://localhost:3306/woosso
    username: admin
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

logging:
  level:
    root: info
    org.springframework.security.web: info
    com.shpark.woosso: debug

server:
  servlet:
    context-path: /api